### ISSUE TITLE
One language overriding the other

### ISSUE THREAD

**Issue by vanessascode** [BuddyForms/BuddyForms-Ultimate-Member#9]
**Describe the bug**
PostLab page is in two languages. I think when matching BuddyForms-Ultimate-Member well together, the it has not occured that that when trying to add the right page from the ENG side, that would create the tab "Add developers" (pic enclosed) and then from the French side to create the tab Developer Form (pic enclosed), one would override the other, meaning you might end up with having an English/French language tab on both pages. @svenl77 - perhaps you can help with this.

**Expected behaviour**
For english there should be the english version of the tab. For french there should be the french version of the tab. 
**Screenshots/replication**
(enclosed)

**Environment details (please complete the following information):**
OS: Mac Version 10.13.6
Google Crome: Version 72.0.3626.109
BuddyForms plugin version: 2.5.1
UltimateMember plugin version: 2.0.53

![postlabENG](https://user-images.githubusercontent.com/18070947/62545480-732ec580-b86a-11e9-9495-e53417ed0c3c.png)
![postlabFRA](https://user-images.githubusercontent.com/18070947/62545493-77f37980-b86a-11e9-824f-d227b6365a4b.png)
![postlabENGaddDev](https://user-images.githubusercontent.com/18070947/62545668-d6205c80-b86a-11e9-9187-192e734a5cf0.png)
![postlabFRAselectpage](https://user-images.githubusercontent.com/18070947/62545752-fa7c3900-b86a-11e9-9458-2bba0b1ffefa.png)
![PostlabENG2](https://user-images.githubusercontent.com/18070947/62545824-1a136180-b86b-11e9-9512-df118fd3bae9.png)
![PostlabFRA2](https://user-images.githubusercontent.com/18070947/62545832-1c75bb80-b86b-11e9-9c90-80d0e6b93131.png)
![PostlabFRAdevForm](https://user-images.githubusercontent.com/18070947/62545838-1e3f7f00-b86b-11e9-9844-363f44683de7.png)

**Comment by vanessascode** [comment]
@gfirem , can you help with that too? I was not entirely sure what causes the problem, so I am not sure if I posted this to the right place.

**Comment by gfirem** [comment]
Yes, I can help you with this, like in the other ticket, with the clone I can take a look into all.

**Comment by vanessascode** [comment]
@gfirem , thank you, sent the credentials to the support e-mail

**Comment by svenl77** [comment]
@vanessascode was this fixed? What is the status? I will close it please reopen if not fixed.
